server:
  port: 8050

spring:
  application:
    name: Menu Management Service
  profiles:
    active: DEV
  data:
    mongodb:
      uri: "mongodb+srv://it20026448:admin@cluster0.pethk6q.mongodb.net/RESTAURENT_DEV?retryWrites=true&w=majority&appName=Cluster0"
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_QjDkjH1k4"