server:
  port: 8050

spring:
  application:
    name: Menu Management Service
  profiles:
    active: DEV
  data:
    mongodb:
      uri: ${MONGO_DB_URI}
  main:
    allow-bean-definition-overriding: true