name: CI/CD Pipeline - Menu Management Service

on:
  push:
    branches: ["master"]
    paths:
      - "menu-management-service/**"
  pull_request:
    branches: ["master"]
    paths:
      - "menu-management-service/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Set up environment variables
        run: echo "MONGO_DB_URI=${{ secrets.DB_URI }}" >> $GITHUB_ENV
      - name: Change to the project directory
        run: cd menu-management-service
      - name: Build with Maven
        run: mvn clean install
        working-directory: ./menu-management-service
