name: CI/CD Pipeline - Men

on:
  push:
    branches: [ "master" ]
    paths:
      - 'menu-management-service/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'menu-management-service/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Change to the project directory
      run: cd menu-management-service
    - name: Build with Maven
      run: mvn clean install
      env:
        MONGO.DB_URI: ${{ secrets.DB_URI }}
      working-directory: ./menu-management-service
