name: Deploy to Amazon EC2

on:
  push:
    branches:
      - master
      - deploy-to-ec2
  pull_request:
    branches:
      - master
      - deploy-to-ec2

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Change to the project directory
        run: cd menu-management-service

      - name: Build with Maven
        run: mvn clean install
        working-directory: ./menu-management-service

      - name: Login to DockerHub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build docker image
        run : docker build -t it20026448/restaurant-management-system .
      
      - name: Publish image to dockerhub
        run: docker push it20026448/restaurant-management-system:latest

  deploy:
    name: Deploy
    runs-on: [aws-ec2]
    needs: build

    steps:
      - name: Pull image from dockerhub
        run: docker pull it20026448/restaurant-management-system:latest
      - name: Delete old container
        run: docker rm -f menu-management-container
      - name: Run docker container
        run: docker run -d -p 8050:8050 --name menu-management-container it20026448/restaurant-management-system:latest