name: CI/CD Pipeline - Menu Management Service

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Set up environment variables
        run: |
          echo "MONGO_DB_URI=${{ secrets.DB_URI }}" >> $GITHUB_ENV
          echo "ISSUER_URI=${{ secrets.ISSUER_URI }}" >> $GITHUB_ENV
      - name: Change to the project directory
        run: cd menu-management-service
      - name: Build with Maven
        run: mvn clean install
        working-directory: ./menu-management-service
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/menu-management-service:latest .
      - name: Publish image to docker hub
        run: docker push ${{secrets.DOCKER_USERNAME}}/menu-management-service:latest
